services:
  web:
    image: node:18-alpine
    build: .
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
    command: [ "node", "index.js" ]

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: JaiAvi10:14
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
